import firebase from 'firebase/app'
import "firebase/auth"
const app = firebase.initializeApp({
    REACT_APP_FIREBASE_API_KEY
REACT_APP_FIREBASE_AUTH_DOMAIN
REACT_APP_FIREBASE_DATABASE_URL
REACT_APP_FIREBASE_PROJECT_ID
REACT_APP_FIREBASE_STORAGE_BUCKET
REACT_APP_FIREBASE_MESSAGING_SENDER_ID
REACT_APP_FIREBASE_APP_ID=  1:353511613996:web:a286a6667006baad131389
REACT_APP_FIREBASE_MEASUREMENT_ID= G-BR8GPB6FZQ
})